### ISSUE TITLE
Black window on startup of client

### ISSUE THREAD

**Issue by mikumikudice** [DomonkosSuranyi/westiny#69]
OS: 5.13.11-1-MANJARO
rust version used to build: 1.47.0
Device data: AMD Ryzen 3 2200G with Radeon Vega Graphics | Memory Size: 6 GB + 512 MB (total is 8gb but radeon card uses the rest of memory)
The terminal output keeps printing ``[INFO][westiny_client::systems::client_connect] Network event: Disconnect(1.2.3.4:5745)`` but nothing happens.

**Comment by DomonkosSuranyi** [comment]
At the current state of the game the client keeps black until successful server connection.
Is your server running?
Could you show the server and client logs?

**Comment by mikumikudice** [comment]
@DomonkosSuranyi where do I find these logs? I couldn't find any of them. Also I tried again to run both server and client, adding the same export arg to the server, but the problem keeps unsolved.

**Comment by DomonkosSuranyi** [comment]
I think the issue here is that the client tries to connect to the server on a different address/port than the one where the server is listening on.

If you don't define a `WESTINY_SERVER_ADDRESS` it will try to find the server on address 0.0.0.0:5745. The server's default is this one too.

So how to solve the problem:
1. Start the server (`cargo run --release --bin westiny_server`)
2. Open another console
3. In the second console run the client **without** defining a `WESTINY_SERVER_ADDRESS`. (`cargo run --release --bin westiny_client`)

It should be able to connect now and your player should be shown instead of the black screen.

If the above solution did not work:
1. Start the server (`cargo run --release --bin westiny_server`)
2. Check the first console-log-line which tells the address where the server is listening on.
3. Open another console
4. In the second console run the client with defining server address. (e.g. `WESTINY_SERVER_ADDRESS="0.0.0.0:5745"cargo run --release --bin westiny_client`)

Please let me know if none helped.

**Comment by DomonkosSuranyi** [comment]
Additional notes:
* The server does not care this env var. It's address can be configured at `resources/server_network.ron`.
* By default westiny does not logs to a file. You can command it to do so setting the env var `AMETHYST_LOG_FILE_PATH`

**Comment by DomonkosSuranyi** [comment]
I've updated the README to make it clear to everyone and additionally added a section to it to explain how to change player name and how to run multiple clients on the same computer.
Have fun ;)

**Comment by mikumikudice** [comment]
I received this error after shutting down:
```
[ERROR][westiny_server::systems::network_messenger] Error during disconnect_client: Could not find address 127.0.0.1:53658 in registry
```
But the game worked as it should (I guess) running both client and server without export flags! I think it's ok to close the issue for now, right?

**Comment by DomonkosSuranyi** [comment]
I'm glad to hear that!
The error message occurred because the server tried to send a 'Disconnect' message to the client while the client was offline already. For now it's okay.
